### ISSUE TITLE
Shortcuts Change

### ISSUE THREAD

**Issue by Njordy** [jedypod/nuke-config#5]
Hi again. 

You have some custom shortcuts in the config, it's great. I do have some custom shortcuts I made using "shortcuteditor.py". The thing is, I have some conflicting shortcuts and would love to delete some of your's. Would you be so kind directing me where exactly located the files I need to put my changes to in your config? :)

---
Offtopic: I actually decided what I want my .nuke folder "to live on dropbox", and sync between OSs/PCs. :) I added my new path to the same env variable path (separate folders for your setup and mine). I've learned what not everything can be used like this, uistate, and nuke configurations for example. I found out what not everything (I have a ton of scripts and gizmos) works this way sadly. Do you know about any limitation for this method? 

Thank you. :)

**Comment by jedypod** [comment]
Hey @Njordy ! 
Super sorry for the delay in getting back to you about this. 

Ideally anything you set in shortcuteditor would override shortcuts set elsewhere. I will have to look into why that is not happening.

Meanwhile, most custom shortcuts are defined at the top of the python module in question so that it is self-contained. For example in [dag.py](https://github.com/jedypod/nuke-config/blob/master/tools/python/nuketools/dag.py), all the shortcuts are defined at the top of the module. Feel free to comment out or delete any of those lines, or changes the shortcuts to be whatever you want!

Hopefully this helps (if this is even still useful after so long)... I'll keep the issue open until I figure out why shortcuteditor is not overriding existing shortcuts properly.

**Comment by jedypod** [comment]
I'm pretty sure I tracked this down... shortcuteditor needs to be imported in menu.py last in order to override everything else. I have made some changes and it should be set up this way now I think!
